### ISSUE TITLE
Playground Clone needs nquads output

### ISSUE THREAD

**Issue by hsolbrig** [fhircat/FHIRCat#25]
Need the nquads tab on the playground

**Comment by ericprud** [comment]
I [replaced nquads with Turtle](https://github.com/fhircat/json-ld.org/commit/735b280f8cf9136ffdb22b80b12ff2d61b85f921#diff-6818b28212f86523d616ee70a27c0b44) a couple days ago. Is this saying that we need nquads back?

**Comment by hsolbrig** [comment]
Would be handy to have both, assuming that the Turtle starts looking a bit more turtle-like.  (namespaces, BNodes as brackets, lists as parens, ...

**Comment by hsolbrig** [comment]
Actually, between "Normalized" and "Table", we're probably good without nquads.  Never mind...

**Comment by ericprud** [comment]
I didn't write a turtifier; i grabbed one from N3.js, so the odds that it gets []s is pretty small. I did, however, add some code to N3.js a while back to serialize lists. I just [added that to playground](https://github.com/fhircat/json-ld.org/commit/27edb1feae5da98d4502339e28cd79c1924feb40) so:
``` JSON
{
  "@context": {
    "ex": "http://example.org/vocab#",
    "xsd": "http://www.w3.org/2001/XMLSchema#",
    "ex:contains": {
      "@container": "@list"
    }
  },
  "@id": "http://example.org/smallInts",
  "ex:contains": [1, 2, 3]
}
```
is rendered as an adequate list:
``` turtle
PREFIX ex: <http://example.org/vocab#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

<http://example.org/smallInts> ex:contains ("1"^^xsd:integer "2"^^xsd:integer "3"^^xsd:integer).
```
