### ISSUE TITLE
Patient gender doesn't reference a context

### ISSUE THREAD

**Issue by hsolbrig** [fhircat/FHIRCat#28]
The `gender` attribute in https://fhircat.org/fhir/contexts/r5/patient.context.jsonld is untyped. 
```
  "gender": {
      "@id": "fhir:Patient.gender"
    },
```
While it is probably overkill to add a context for R4 string values, we still need to map the `value` tag and extension:
```
  "gender": {
       "@id": "fhir:Patient.gender",
      "extension": {
           "@id": "fhir:Element.extension",
           "@context": "extension.context.jsonld"
       },
       "value": {
           "@id": "fhir:value"
      },
```

(Alternative is to have a `string.context.jsonld`)

**Comment by cendle** [comment]
Added "@context": "string.context.jsonld" for object that didn't previously have a context and their type was "code"
